#region Copyright (c) 2016 Atif Aziz. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#endregion

// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 24 Jun 2016 05:18:19 GMT

namespace DeJson
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Jayrock.Json;
    using Mannex.Collections.Generic;
    using MoreLinq;

    // There are only 16 Func delegates available in the BCL but more are
    // needed to work with structures that have more than 16 members.

    delegate TResult Selector<T, TResult>(T arg);
    delegate TResult Selector<T1, T2, TResult>(T1 arg1, T2 arg2);
    delegate TResult Selector<T1, T2, T3, TResult>(T1 arg1, T2 arg2, T3 arg3);
    delegate TResult Selector<T1, T2, T3, T4, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4);
    delegate TResult Selector<T1, T2, T3, T4, T5, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17, T18 arg18);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17, T18 arg18, T19 arg19);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17, T18 arg18, T19 arg19, T20 arg20);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17, T18 arg18, T19 arg19, T20 arg20, T21 arg21);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17, T18 arg18, T19 arg19, T20 arg20, T21 arg21, T22 arg22);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17, T18 arg18, T19 arg19, T20 arg20, T21 arg21, T22 arg22, T23 arg23);
    delegate TResult Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, TResult>(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16, T17 arg17, T18 arg18, T19 arg19, T20 arg20, T21 arg21, T22 arg22, T23 arg23, T24 arg24);

    partial class JsonImporter
    {
        static readonly Type[] SelectorTypes =
        {
            /* [ 1] */ typeof(Selector<,>),
            /* [ 2] */ typeof(Selector<,,>),
            /* [ 3] */ typeof(Selector<,,,>),
            /* [ 4] */ typeof(Selector<,,,,>),
            /* [ 5] */ typeof(Selector<,,,,,>),
            /* [ 6] */ typeof(Selector<,,,,,,>),
            /* [ 7] */ typeof(Selector<,,,,,,,>),
            /* [ 8] */ typeof(Selector<,,,,,,,,>),
            /* [ 9] */ typeof(Selector<,,,,,,,,,>),
            /* [10] */ typeof(Selector<,,,,,,,,,,>),
            /* [11] */ typeof(Selector<,,,,,,,,,,,>),
            /* [12] */ typeof(Selector<,,,,,,,,,,,,>),
            /* [13] */ typeof(Selector<,,,,,,,,,,,,,>),
            /* [14] */ typeof(Selector<,,,,,,,,,,,,,,>),
            /* [15] */ typeof(Selector<,,,,,,,,,,,,,,,>),
            /* [16] */ typeof(Selector<,,,,,,,,,,,,,,,,>),
            /* [17] */ typeof(Selector<,,,,,,,,,,,,,,,,,>),
            /* [18] */ typeof(Selector<,,,,,,,,,,,,,,,,,,>),
            /* [19] */ typeof(Selector<,,,,,,,,,,,,,,,,,,,>),
            /* [20] */ typeof(Selector<,,,,,,,,,,,,,,,,,,,,>),
            /* [21] */ typeof(Selector<,,,,,,,,,,,,,,,,,,,,,>),
            /* [22] */ typeof(Selector<,,,,,,,,,,,,,,,,,,,,,,>),
            /* [23] */ typeof(Selector<,,,,,,,,,,,,,,,,,,,,,,,>),
            /* [24] */ typeof(Selector<,,,,,,,,,,,,,,,,,,,,,,,,>),
        };

        static Func<JsonReader, TResult> CreateImporter<T1, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Selector<T1, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Selector<T1, T2, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Selector<T1, T2, T3, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Selector<T1, T2, T3, T4, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Selector<T1, T2, T3, T4, T5, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Selector<T1, T2, T3, T4, T5, T6, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Selector<T1, T2, T3, T4, T5, T6, T7, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Func<JsonReader, T18> r18,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);
                var v18 = default(T18);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            case 18: v18 = r18(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Func<JsonReader, T18> r18,
            Func<JsonReader, T19> r19,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);
                var v18 = default(T18);
                var v19 = default(T19);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            case 18: v18 = r18(reader); break;
                            case 19: v19 = r19(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Func<JsonReader, T18> r18,
            Func<JsonReader, T19> r19,
            Func<JsonReader, T20> r20,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);
                var v18 = default(T18);
                var v19 = default(T19);
                var v20 = default(T20);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            case 18: v18 = r18(reader); break;
                            case 19: v19 = r19(reader); break;
                            case 20: v20 = r20(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Func<JsonReader, T18> r18,
            Func<JsonReader, T19> r19,
            Func<JsonReader, T20> r20,
            Func<JsonReader, T21> r21,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);
                var v18 = default(T18);
                var v19 = default(T19);
                var v20 = default(T20);
                var v21 = default(T21);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            case 18: v18 = r18(reader); break;
                            case 19: v19 = r19(reader); break;
                            case 20: v20 = r20(reader); break;
                            case 21: v21 = r21(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Func<JsonReader, T18> r18,
            Func<JsonReader, T19> r19,
            Func<JsonReader, T20> r20,
            Func<JsonReader, T21> r21,
            Func<JsonReader, T22> r22,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);
                var v18 = default(T18);
                var v19 = default(T19);
                var v20 = default(T20);
                var v21 = default(T21);
                var v22 = default(T22);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            case 18: v18 = r18(reader); break;
                            case 19: v19 = r19(reader); break;
                            case 20: v20 = r20(reader); break;
                            case 21: v21 = r21(reader); break;
                            case 22: v22 = r22(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Func<JsonReader, T18> r18,
            Func<JsonReader, T19> r19,
            Func<JsonReader, T20> r20,
            Func<JsonReader, T21> r21,
            Func<JsonReader, T22> r22,
            Func<JsonReader, T23> r23,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);
                var v18 = default(T18);
                var v19 = default(T19);
                var v20 = default(T20);
                var v21 = default(T21);
                var v22 = default(T22);
                var v23 = default(T23);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            case 18: v18 = r18(reader); break;
                            case 19: v19 = r19(reader); break;
                            case 20: v20 = r20(reader); break;
                            case 21: v21 = r21(reader); break;
                            case 22: v22 = r22(reader); break;
                            case 23: v23 = r23(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23);
                }
            };
        }

        static Func<JsonReader, TResult> CreateImporter<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, TResult>(
            IEnumerable<string> names,
            Func<JsonReader, T1> r1,
            Func<JsonReader, T2> r2,
            Func<JsonReader, T3> r3,
            Func<JsonReader, T4> r4,
            Func<JsonReader, T5> r5,
            Func<JsonReader, T6> r6,
            Func<JsonReader, T7> r7,
            Func<JsonReader, T8> r8,
            Func<JsonReader, T9> r9,
            Func<JsonReader, T10> r10,
            Func<JsonReader, T11> r11,
            Func<JsonReader, T12> r12,
            Func<JsonReader, T13> r13,
            Func<JsonReader, T14> r14,
            Func<JsonReader, T15> r15,
            Func<JsonReader, T16> r16,
            Func<JsonReader, T17> r17,
            Func<JsonReader, T18> r18,
            Func<JsonReader, T19> r19,
            Func<JsonReader, T20> r20,
            Func<JsonReader, T21> r21,
            Func<JsonReader, T22> r22,
            Func<JsonReader, T23> r23,
            Func<JsonReader, T24> r24,
            Selector<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, TResult> selector)
        {
            var map = names.Index(1).ToDictionary(e => e.Value, e => e.Key, StringComparer.OrdinalIgnoreCase);
            return reader =>
            {
                var v1 = default(T1);
                var v2 = default(T2);
                var v3 = default(T3);
                var v4 = default(T4);
                var v5 = default(T5);
                var v6 = default(T6);
                var v7 = default(T7);
                var v8 = default(T8);
                var v9 = default(T9);
                var v10 = default(T10);
                var v11 = default(T11);
                var v12 = default(T12);
                var v13 = default(T13);
                var v14 = default(T14);
                var v15 = default(T15);
                var v16 = default(T16);
                var v17 = default(T17);
                var v18 = default(T18);
                var v19 = default(T19);
                var v20 = default(T20);
                var v21 = default(T21);
                var v22 = default(T22);
                var v23 = default(T23);
                var v24 = default(T24);

                using (var e = Members(reader))
                {
                    while (e.MoveNext())
                    {
                        switch (map.Find(e.Current))
                        {
                            case 1: v1 = r1(reader); break;
                            case 2: v2 = r2(reader); break;
                            case 3: v3 = r3(reader); break;
                            case 4: v4 = r4(reader); break;
                            case 5: v5 = r5(reader); break;
                            case 6: v6 = r6(reader); break;
                            case 7: v7 = r7(reader); break;
                            case 8: v8 = r8(reader); break;
                            case 9: v9 = r9(reader); break;
                            case 10: v10 = r10(reader); break;
                            case 11: v11 = r11(reader); break;
                            case 12: v12 = r12(reader); break;
                            case 13: v13 = r13(reader); break;
                            case 14: v14 = r14(reader); break;
                            case 15: v15 = r15(reader); break;
                            case 16: v16 = r16(reader); break;
                            case 17: v17 = r17(reader); break;
                            case 18: v18 = r18(reader); break;
                            case 19: v19 = r19(reader); break;
                            case 20: v20 = r20(reader); break;
                            case 21: v21 = r21(reader); break;
                            case 22: v22 = r22(reader); break;
                            case 23: v23 = r23(reader); break;
                            case 24: v24 = r24(reader); break;
                            default: reader.Skip(); break;
                        }
                    }
                    return selector(v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24);
                }
            };
        }
    }
}
